#%RAML 1.0 DataType

type: array
items:
    type: object
    properties:
      code:
        type: string
        required: true
        maxLength: 5
        example:
          "AAPL"
      exchange:
        type: string
        required: true
        maxLength: 10
        example:
          NASDAQ
      operation:
        type: string
        required: true
        maxLength: 4
        enum: ["sell", "buy"]
      price:
        type: number
        required: true
        example:
          123.50
      quantity:
        type: integer
        required: true
        example:
          20



        
